# Generated by Django 3.0.1 on 2020-01-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('importannt', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='core.Todo')),
            ],
        ),
    ]
